# Generated by Django 4.1.1 on 2022-09-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postagem',
            old_name='data_punlicacao',
            new_name='data_publicacao',
        ),
    ]
