# Generated by Django 4.1.1 on 2022-09-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_data_punlicacao_postagem_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
